### ISSUE TITLE
Flash cards created with Moodle are broken.

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-flashcards#11]
Flash cards created in Moodle are broken.

Hello @fnoks ,

If you create a flash card H5P-activity in Moodle it doesn't load the cards at all and you cannot even change the page (the arrow is still highlighted with glowing outline). It works in version 1.4.0 but not in 1.5.3.

If I do flash cards activity in h5p.org and upload it to moodle it works perfectly but not when I direcly create it with moodle H5P-activity.

Tested with mod_hvp 1.5 and Flashcards (1.5.3) & Moodle 3.1

Still works in mod_hvp 1.3 and Flashcards (1.4.0) & Moodle 3.1

![flash1](https://user-images.githubusercontent.com/15193418/32433219-f8572d26-c2e2-11e7-82b9-2597ef3acadc.PNG)

![flash2](https://user-images.githubusercontent.com/15193418/32433229-fdad66dc-c2e2-11e7-8b55-c4106fa5b44c.PNG)

![flash3](https://user-images.githubusercontent.com/15193418/32433237-01d092de-c2e3-11e7-83a7-18b2833e3f3e.png)

**Comment by fnoks** [comment]
Could you please check the JavaScript console to see if there are any error messages there?

**Comment by Jarvil** [comment]
Hello,

Error is;

Uncaught TypeError: H5P.JoubelUI.createTip(...).attr is not a function
    at C.H5P.Flashcards.C.addCard (flashcards.js?ver=1.5.3:288)
    at C.H5P.Flashcards.C.cardsLoaded (flashcards.js?ver=1.5.3:175)
    at HTMLImageElement.load (flashcards.js?ver=1.5.3:66)
    at HTMLImageElement.dispatch (jquery.js?ver=2017083100:2)
    at HTMLImageElement.v.handle (jquery.js?ver=2017083100:2)

**Comment by fnoks** [comment]
Could you check which version H5P.JoubelUI is? Go to the library admin page and search for "Joubel UI"

**Comment by Jarvil** [comment]
Hello,

Versions are 

Joubel UI (1.2.13) |   | 0 | 32 | 68 |  
-- | -- | -- | -- | -- | --
Joubel UI (1.3.5) |   | 0 | 24 | 19

![joubelui](https://user-images.githubusercontent.com/15193418/32821228-fd1152f2-c9da-11e7-90e7-818b9d0bd4f7.PNG)

**Comment by fnoks** [comment]
It's hard to say what is going on here. Is it possible for you to share the H5P here or send it to me on email?

**Comment by Jarvil** [comment]
Hello,

Here it is

**Comment by fnoks** [comment]
Thank you for sharing the H5P with us.

For some reason, there is a <BR> in the first cards tip. You can fix it by just opening the editor, and make sure you delete anything inside the tip wysiyg and the save.

The code should have handled this. I am looking into a fix.

**Comment by fnoks** [comment]
The fix for this issue is released in Flashcards 1.5.4
